--ANTES DE CREAR USUSARIOS 
ALTER SESSION SET "_oracle_script"=TRUE;

--PROCEDEMOS A CREAR USUARIO
-- NOMBRE DE USUARIO USER01 Y CONTRASEÑA USER01
CREATE USER USER01 IDENTIFIED BY user01;

--PARA VER TODOS LOS USUARIOS CREADOS
SELECT * FROM ALL_USERS;

SELECT * FROM DBA_USERS;

--UN USUARIO DESPUES DE SER CREADO SE LE DEBE ASIGNAR PERMISOS
--SINO NO SE PUEDE CONECTAR

GRANT CONNECT TO USER01;

--PROBAMOS LA CONEXION Y YA FUNCIONA

--CREAMOS OTRO USUARIO CON OTROS PARAMETROS
CREATE USER USER02 IDENTIFIED BY user02
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP;

--SE ASIGNA PERMISOS
GRANT CONNECT TO USER02;

--SI NOS CONECTAMOS AL USUARIO Y QUEREMOS CREAR UNA TABLA 
--NO NOS DEJARA POR NO TENER PERMISOS, POR LO QUE SE LE DEBE ASIGNAR EL PERMISO RESPECTIVO

GRANT RESOURCE TO USER02;


--INTENTAMOS CREAR UNA TABLA EN USER02 PARA ELLO NOS CONECTAMOS EN SQLPLUS AL USER02

CREATE TABLE TABLE01 (CODIGO NUMBER);

--USAMOS ALGUNAS VISTAS PARA HACER ALGUNAS CONSULTAS
SELECT * FROM DBA_USERS WHERE USERNAME='USER02';

--PARA CONSULTAR SOBRE UNA TABLA
SELECT * FROM DBA_TABLES WHERE TABLE_NAME='TABLA01';


--PARA CAMBIAR SU CONTRASEÑA LO PUEDE HACER UN ADMINISTRADOR O EL PROPIO USUARIO
ALTER USER USER02 IDENTIFIED BY 12345;

--PODEMOS CAMBIAR SU TABLESPACE
CREATE TABLESPACE INF001 DATAFILE 'D:\app\Desktop\product\21c\oradata\XE\INF001.DBF' SIZE 20M;

--CAMBIAMOS EL TABLESPACE PORDEFECTO PARA EL USER02
ALTER USER USER02 DEFAULT TABLESPACE INF001;


--CREAMOS UNA NUEVA TABLA EN USER02
--NOS CONECTAMOS A PLSQL
CREATE TABLE TABLA02 (CODIGO NUMBER);
--COMO NO NOS DEJA DEBEMOS ASIGNARLE UNA CUOTA DE ESPACIO

 --ASIGNAMOS UNA CUOTA DE ESPACIO EN EL TABLESPACE
 ALTER USER  USER02 QUOTA 10M ON INF001;
 
ALTER USER USER02 QUOTA UNLIMITED ON INF001;

ALTER USER USER02 QUOTA 5M ON INF001  QUOTA 0 ON USERS;

--COMO VER CUANTO ESPACIO TIENEN ASIGNADO MIS USUARIOS
SELECT * FROM DBA_TS_QUOTAS;

SELECT * FROM USER_TS_QUOTAS;

--COMO BLOQUEAR O DESBLOQUEAR USUARIOS
ALTER USER USER02 ACCOUNT LOCK;

ALTER USER USER02 ACCOUNT UNLOCK;

SELECT * FROM DBA_USERS;

--BLOQUEAR Y EXPIRAR LA CONTRASEÑA
ALTER USER USER02 PASSWORD EXPIRE;


--BORRAR UN USUARIO SE USA DROP USER
--PRIMERO CREAMOS UN NUEVO USUARIO
CREATE USER USER04 IDENTIFIED BY user04;

DROP USER USER04;


CREATE USER USER04 IDENTIFIED BY user04;

CREATE TABLE USER04.TABLA01 (CODIGO NUMBER);

ALTER USER USER04 QUOTA UNLIMITED ON USERS;

INSERT INTO USER04.TABLA01 VALUES(200);
COMMIT;

DROP USER USER04 CASCADE;


--ASIGNACION DE PRIVILEGIOS DE SISTEMA Y DE OBJETOS

CREATE USER USER03 IDENTIFIED BY user03;

GRANT CONNECT TO USER03;

--PROBAMOS SI SE CONECTA EN SQLPLUS
SQLPLUS USER03/user03

--UNA VEZ CONECTADO HACEMOS LA PRUEBA DE CREAR TABLA
create TABLA01 (CODIGO NUMBER);

CREATE SYNONYM PRUEBA01 TO TABLA01

--LE ASIGNAMOS PERMISO DE CREACION Y RECIEN PODRNA CREAR TABLAS
GRANT CREATE TABLE TU USER03;

GRANT CREATE SYNONYM TO USER03;

GRANT CREATE ANY TABLE TO USER03;


--ASIGNAR PRIVILEGIOS QUE SE HEREDAN
--SE ESTA ASIGNANDO PERMISOS PARA CREAR PRODCEDIMEINTOS Y ADERMAS 
--PAARA QUE EL PUEDA ASIGNAR A OTROS USUARIOS

GRANT CREATE PROCEDURE TO USER02 WITH ADMIN OPTION;


--PARA QUITAR `PRIVILEGIOS SE USA REVOKE
REVOKE CREATE PROCEDURE FROM USER02;



--*************************************
--ASIGNACION DE PRIVILEGIOS DE OBJETOS
--DAR PERMISO ENTRE DISTINTOS USUARIOS
--ME CONECTO COO USER02 EN SQLDEVELOPER
--CREAMOS UNA TALA PRODUCTO EN EL USER02
--*****************************************

CREATE TABLE MENU
(	CODMENU NUMBER,
	NOMBREMENU VARCHAR2(50)
);

INSERT INTO MENU VALUES  (1,'FILET MIGNON');

INSERT INTO MENU VALUES (2,'MOJITO');

COMMIT;


GRANT SELECT,UPDATE ON MENU TO USER03;

--PROBAMOS DE NUEVO CON EL USUARIO USER03 Y FUNCIONA

--INTENTAMOS HACER UN UPDATE  Y DELETE
UPDATE USER02.MENU SET NOMBRE='PISCO SOUR' WHERE CODMENU=2;

DELETE USER02.MENU WHERE CODMENU=2;

GRANT ALL ON MENU TO USER03;


--ASIGNAR PERMISOS SOBRE COLUMNAS DE TABLAS
CREATE TABLE ALUMNOS(
CODALUMNO NUMBER,
NOMBRES VARCHAR2(50),
APELLIDOS VARCHAR2(100));


GRANT UPDATE (APELLIDOS) ON ALUMNOS TO USER03;

GRANT INSERT (CODALUMNO,NOMBRES) ON ALUMNOS TO USER03;

--INTENTAMOS INSERTAR REGISTROS PERO NO DEJARA POR NO TENER PERMISO
--Y ACTUALIZAMOS REGOISTROS

INSERT INTO USER02.ALUMNOS VALUES (1,'JORGE','CHOQUE MORALES');

UPDATE USER02.ALUMNOS SET APELLIDO='LOPEZ' WHERE CODALUMNO=1;

--COMO HEREDAR PRIVILEGIOS DE OBJETOS ASIGNAMOS A USER03

GRANT  SELECT ON MENU TO USER03 WITH GRANT OPTION;

GRANT SELECT USER02.MENU TO USER01;

--QUITAR PRIVILEGIOS DE OBJETOS

REVOKE SELECT ON MENU FROM USER03;

REVOKE ALL ON MENU FROM USER03;







--*************************
--COMO VER LOS PARAMETROS DEL ARCHIVO PROFILE POR DEFECTO

SELECT * FROM DBA_PROFILES WHERE PROFILE='DEFAULT'
ORDER BY RESOURCE_TYPE,RESOURCE_NAME;

SELECT USERNAME,PROFILE FROM DBA_USERS WHERE USERNAME = 'HR';


--PARA CREAR UN PRPOFILE PRIMERO DEBEMOS ACTIVAR
ALTER SESSION SET "_oracle_script"=TRUE;


--PROCEDEMOS A CREAR EL PROFILE

CREATE PROFILE INF272_USERS LIMIT
        SESSIONS_PER_USER   UNLIMITED
        CPU_PER_SESSION       UNLIMITED
        CPU_PER_CALL             3000
        CONNECT_TIME             15;


--AHORA CREAMOS UN USUARIO Y LE ASIGNAMOS ESE PROFILE

CREATE USER INF272_USER10 IDENTIFIED BY 12345
PROFILE INF272_USERS;

--CONSULTAMOS LA ASIGNACION
SELECT USERNAME,PROFILE FROM DBA_USERS WHERE username = 'INF272_USER10';





