--VISTAS PARA VER TODOS LOS USUARIOS
SELECT * FROM DBA_USERS;  

SELECT * FROM ALL_USERS;  

SELECT * FROM USER_USERS;


--VISTAS PARA VER LOS PERMISOS DE UN USUARIO
SELECT * FROM DBA_SYS_PRIVS;

SELECT * FROM DBA_SYS_PRIVS WHERE GRANTEE = 'HR';

--VER QUE PERMISOS TIENE RESOURCE
SELECT * FROM DBA_SYS_PRIVS WHERE GRANTEE='RESOURCE';  


SELECT * FROM ROLE_SYS_PRIVS;

SELECT * FROM USER_SYS_PRIVS;


SELECT * FROM USER_TAB_PRIVS;

SELECT * FROM ALL_TAB_PRIVS;

SELECT * FROM ROLE_TAB_PRIVS;

SELECT * FROM DBA_TAB_PRIVS;



--MUESTRA TODOS LOS ROLES QUE EXISTEN
SELECT * FROM DBA_ROLES;

--MUESTRA LOS ROLES QUE POSEE EL USUARIO
SELECT * FROM DBA_ROLE_PRIVS;

SELECT * FROM USER_ROLE_PRIVS;

SELECT * FROM ROLE_ROLE_PRIVS;

SELECT * FROM ALL_COL_PRIVS;



--VISTAS PARA TABLESPACES
SELECT * FROM DBA_TABLESPACES;

SELECT * FROM DBA_DATA_FILES;

SELECT * FROM DBA_TEMP_FILES;

SELECT * FROM V$DATAFILE;

SELECT * FROM V$TEMPFILE;

SELECT * FROM DBA_FREE_SPACE;

SELECT * FROM DBA_FREE_SPACE WHERE TABLESPACE_NAME='USERS';


--VER EL ESPACIO DETERMINADO DEL USUARIO ACTUAL
SELECT USERNAME,DEFAULT_TABLESPACE FROM USER_USERS;



--SE �EDE HACER ESTO EN SQLPLUS PARA VER MAS PAUSADO
SET PAGESIZE 10
SET PAUSE ON
SET PAUSE "PRESINE ENTER PARA CONTINUAR...."
SELECT VIEW_NAME FROM ALL_VIEWS;

--SESIONES ACTIVAS
SELECT * FROM V$SESSION;

--PROCESOS QUE SE ESTAN EJECUTANDO
SELECT * FROM V$PROCESS;

--PARA VER TODOS LOS TIPOS DE VISTAS QUE TENEMOS
SELECT * FROM V$FIXED_TABLE WHERE NAME LIKE 'V$%';



--COMANDOS PARA TABLESPACE
--CREACION DE TABLESPACES
create tablespace FCPN 
datafile 'D:\app\Desktop\product\21c\oradata\XE\fcpn.dbf'
size 10M

create tablespace matriculas 
datafile 'D:\app\Desktop\product\21c\oradata\XE\matricula01.dbf' size 5M, 
'D:\app\Desktop\product\21c\oradata\XE\matricula02.dbf' size 10M;





CREATE TABLESPACE TBS1 
DATAFILE 'D:\app\Desktop\product\21c\oradata\XE\tbs1.dbf'
SIZE 100m REUSE EXTENT MANAGEMENT LOCAL AUTOALLOCATE;
  
--AUTOALLOCATE   EXTENSIONES DE  64K, 1M, 8M, 64M
--UNIFORM   SIZE XM

CREATE TABLE TABLA1 (C1 VARCHAR2(50)) 
TABLESPACE TBS1 STORAGE (INITIAL 100K);

CREATE TABLE TABLA2 (C1 VARCHAR2(50)) 
TABLESPACE TBS1 STORAGE  (INITIAL 2M);

CREATE TABLE TABLA3 (C1 VARCHAR2(50)) 
TABLESPACE TBS1 STORAGE (INITIAL 950K);


--VISTAS PARA VER LOS TABLESPACES
SELECT * FROM DBA_TABLES;

SELECT * FROM DBA_TABLES WHERE TABLE_NAME='DEPARTMENTS';


--PARA VER LOS SEGMENTS Y EXTENTS CREADOS

SELECT * FROM DBA_SEGMENTS WHERE SEGMENT_NAME='TABLA1';
SELECT * FROM DBA_EXTENTS WHERE SEGMENT_NAME='TABLA1';


--CREATE TABLESPACE CON UNIFORM
CREATE TABLESPACE TBS2 
DATAFILE 'D:\app\Desktop\product\21c\oradata\XE\tbs2.dbf' 
SIZE 100m REUSE EXTENT MANAGEMENT LOCAL UNIFORM SIZE 1M;

--CREAMOS TABLAS EN ESE ESPACIO  
CREATE TABLE TABLA4 (C1 VARCHAR2(50)) 
TABLESPACE TBS2 STORAGE (INITIAL 100K);

CREATE TABLE TABLA5 (C1 VARCHAR2(50)) 
TABLESPACE TBS2 STORAGE (INITIAL 4M);


--A�ADIR FICHERO ADICIONAL A UN TABLESPACE
ALTER TABLESPACE TBS2 
ADD DATAFILE 
'D:\app\Desktop\product\21c\oradata\XE\tbs2a.dbf'
SIZE 50M;


--CAMBIAR ESTADOS DEL TABLESPACE
ALTER TABLESPACE "TBS2" READ ONLY;

--CREAR TABLA
CREATE TABLE TABLA6 (C1 VARCHAR2(50)) 
TABLESPACE TBS2 STORAGE (INITIAL 4M);

--CAMBIAR A LECTURA ESCRITURA EL TABLESPACE
ALTER TABLESPACE "TBS2" READ WRITE;

--POER FUERA DE LINEA EL TABLESPACE
ALTER TABLESPACE "TBS2" OFFLINE NORMAL;

ALTER TABLESPACE "TBS2" OFFLINE TEMPORARY;

ALTER TABLESPACE "TBS2" OFFLINE IMMEDIATE;

--PONER EN LINEA UN TABLESPACE
ALTER TABLESPACE "TBS2" ONLINE;

--AUTOEXTENDER FICHEROS
CREATE TABLESPACE TBS3 DATAFILE
'D:\app\Desktop\product\21c\oradata\XE\tbs3.dbf'
 SIZE 1M AUTOEXTEND ON NEXT 1M  MAXSIZE 250M;
 
--CREACION DE TABLAS
CREATE TABLE AUTO1 (DATOS VARCHAR2(100)) 
STORAGE(INITIAL 500K) TABLESPACE TBS3;

INSERT INTO AUTO1 VALUES ('datos de prueba...............');
INSERT INTO AUTO1 SELECT * FROM AUTO1;

ALTER DATABASE 
DATAFILE 'D:\app\Desktop\product\21c\oradata\XE\TBS3.dbf' 
AUTOEXTEND OFF;

ALTER DATABASE 
DATAFILE 'D:\app\Desktop\product\21c\oradata\XE\TBS3.dbf' 
AUTOEXTEND ON NEXT 1M  MAXSIZE 250M;

--A�ADIR NUEVO FICHERO AUTOEXTEND
ALTER TABLESPACE TBS3 
ADD DATAFILE 'D:\app\Desktop\product\21c\oradata\XE\tbs3-A.dbf' 
SIZE 10M AUTOEXTEND ON NEXT 512K MAXSIZE 250M;

--CAMBIAR EL TAMA�O DE UN DATAFILE
ALTER DATABASE DATAFILE 
'D:\app\Desktop\product\21c\oradata\XE\tbs3-A.dbf'
RESIZE 100M;

--MOVER Y RENOMBRAR DATAFILE
SELECT * FROM DBA_DATA_FILES;

-- RENOMBRAR UN DATAFILE
ALTER DATABASE MOVE DATAFILE 'D:\app\Desktop\product\21c\oradata\XE\tbs3-A.dbf' 
TO 'D:\app\Desktop\product\21c\oradata\XE\tbs3-B.dbf';


--MOVER UN DATA FILE
ALTER DATABASE MOVE DATAFILE 'D:\app\Desktop\product\21c\oradata\XE\tbs3-B.dbf'
TO 'D:\app\Desktop\product\21c\oradata\XE\bbdd\tbs3-nuevo.dbf' ;



--BORRAR TABLESPACES
SELECT * FROM DBA_TABLESPACES;

DROP TABLESPACE TBS3;

DROP TABLESPACE TBS3 INCLUDING CONTENTS;

DROP TABLESPACE TBS2 INCLUDING CONTENTS
AND DATAFILES;